name: Build and Cache

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-darwin]
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: aarch64-darwin
            os: macos-latest
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: 0rvar
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    # - name: Set up QEMU (for aarch64-linux)
    #   if: matrix.system == 'aarch64-linux'
    #   uses: docker/setup-qemu-action@v3
    #   with:
    #     platforms: arm64
    
    - name: Build packages
      run: |
        echo "Building for ${{ matrix.system }}"
        nix build .#v7 .#v6
        # nix build --print-build-logs --system ${{ matrix.system }} .#v7 .#v6
    
    # - name: Check outputs
    #   run: |
    #     nix path-info .#v7 .#v6 --system ${{ matrix.system }}
    #     nix store verify --system ${{ matrix.system }} $(nix path-info .#v7 .#v6)
    
    # - name: Test binaries
    #   run: |
    #     nix run .#v7 --system ${{ matrix.system }} -- --version
    #     nix run .#v6 --system ${{ matrix.system }} -- --version
    
    # - name: Push to Cachix
    #   if: github.event_name == 'push'
    #   run: |
    #     cachix push dx-dioxus $(nix path-info .#v7 .#v6 --system ${{ matrix.system }})